#!/bin/zsh
#─────────────────────────────────────────────────────────────────
# Initialize links
#
# AUTHOR:  Ludovic Vigouroux <ludo@mundoludo.fr>
# CREATED: December 2011
#─────────────────────────────────────────────────────────────────

create_links() {
	local location
	local dir

	for link in ${(ok)links}; do
		# retrieve file
		if [[ -n $links_location && -n $links_location[$link] ]]; then
			location=$treepathslabel[$link_location[$link]]
		else
			location=$link_path
		fi
		file=$location/$link
		link=$links[$link]

		# create link
		if [[ -e $link && ! -L $link ]]; then
			# merge previous existing file
			mv $link ${link}.bak
			vimdiff $file ${link}.bak
		fi

		# create new link
		ln -sfv $file $link
	done
}


# retrieve this file location
pushd "$(dirname ${0})"
script_location=$(pwd)
popd

# read config command
. $script_location/read-config-safe links links_location $*

# load directories path
. $script_location/traverse-tree -q $*

link_path=$treepathslabel[etc]

create_links
# vim: set filetype=zsh:
