#!/bin/zsh
#─────────────────────────────────────────────────────────────────
# Retrieve various sources
#
# author:  Ludovic Vigouroux <ludo@mundoludo.fr>
# created: December 2011
# Free to use, modify and redistribute.
#─────────────────────────────────────────────────────────────────
setopt null_glob

#─────────────────────────────────────────────────────────────────
# Clone sources
#─────────────────────────────────────────────────────────────────
retrieve_src() {
	local destination
	local dir

	for project in ${(ok)src}; do
		print -- $project
		if [[ -n $src_destination && -n $src_destination[$project] ]]; then
			destination=$treepathslabel[$src_destination[$project]]
		else
			destination=$src_path
		fi
		dir=$destination/$project
		if [[ -d $dir ]]; then
			files=($dir/*)
			if [[ ${#files[@]} -gt 0 ]]; then
				cd $dir && git pull
			else
				rmdir $dir && git clone $src[$project] $dir
			fi
		else
			git clone $src[$project] $dir
		fi
	done
}

# retrieve this file location
pushd "$(dirname ${0})"
script_location=$(pwd)
popd

# read config command
. $script_location/load-config src src_destination $*

# load directories path
. $script_location/traverse-tree -q $*

src_path=$treepathslabel[src]

retrieve_src

# vim: set filetype=zsh:
