#!/bin/zsh
#─────────────────────────────────────────────────────────────────
# Add a source to path
#
# author:  Ludovic Vigouroux <ludo@mundoludo.fr>
# created: January 2013
# Free to use, modify and redistribute.
#─────────────────────────────────────────────────────────────────

# retrieve this file location
pushd "$(dirname ${0})"
script_location=$(pwd)
popd

# read config command
. $script_location/load-config src src_destination src_bin $*

# load directories path
. $script_location/traverse-tree -q $*
src_path=$treepathslabel[src]

usage () {
	print -- "src_bin config is missing"
	exit 1
}

export_path() {

	src_name=$1
	[ -z $src_name ] && usage
	if [[ -n $src_destination && -n $src_destination[$src_name] ]]; then
		location=$treepathslabel[$src_destination[$src_name]]
	else
		location=$src_path
	fi
	dir=$location/$src_name
	if [[ -d $dir ]]; then
		print -- '[[ -n ${path[(r)'$dir']} ]] || path=('$dir' $path)'
	fi
}

for src_name in $src_bin; do
	export_path $src_name
done

# vim: set filetype=zsh:
