#!/bin/zsh
#─────────────────────────────────────────────────────────────────
# Initialize a local directories hierarchy
#
# author:  Ludovic Vigouroux <ludo@mundoludo.fr>
# created: October 2011
#─────────────────────────────────────────────────────────────────
setopt null_glob

make_bookmarks() {
  local bookmarks
  local outputs

  # bookmark for every directories in treepath
  for key in ${(k)treepaths}; do
		set_path $key $treepaths[$key]
    # and for every directories inside those
    for dir in ${treepaths[$key]}/*(/); do
			set_path ${dir:t} $dir
    done
  done

  for line in ${(o)outputs}; do
    print -- "typeset -gx" $line
  done

  echo : $bookmarks
}

set_path() {
	path_name=$1
	shift
	path_location=$*
	cleanname=$(echo $path_name | sed 's/\s//g' | sed 's/^[_0-9]*//g' |sed 's/[\.@-]//g')
	outputs=($outputs $cleanname=\"$path_location\")
	bookmarks=($bookmarks $cleanname)
}

# retrieve this file location
pushd "$(dirname ${0})"
script_location=$(pwd)
popd

# load directories path
. $script_location/traverse-tree -q $*

make_bookmarks

# vim: set filetype=zsh:
