#!/bin/zsh
#─────────────────────────────────────────────────────────────────
# Initialize a new share
#
# usage:   init-share [config file]
#
# author:  Ludovic Vigouroux <ludo@mundoludo.fr>
# created: December 2011
#─────────────────────────────────────────────────────────────────

#─────────────────────────────────────────────────────────────────
# Create group if needed
#─────────────────────────────────────────────────────────────────
create_group () {
	if ! grep -q $group_name /etc/group; then
		groupadd --gid $group_id $group_name
	fi
}

#─────────────────────────────────────────────────────────────────
# Create share if needed
#─────────────────────────────────────────────────────────────────
create_share () {
	if ! [[ -d $share ]]; then
		mkdir -p $share || exit 1
		chmod 2775 $share
		chgrp $group_name $share
	fi
}

#─────────────────────────────────────────────────────────────────
# Install new share with values from config
#─────────────────────────────────────────────────────────────────
install_share () {

	# clean share values
	share=$root_location
	[[ -z $share ]] &&
		print -- "Failed to retrieve share location. Aborting" &&
		exit 1
	group_name=$group_name
	[[ -z $group_name ]] &&
		print -- "Failed to retrieve group_name. Aborting" &&
		exit 1
	groupid=$group_id
	[[ -z $group_id ]] &&
		print -- "Failed to retrieve group_id. Aborting" &&
		exit 1

	create_group
	create_share
}

#─────────────────────────────────────────────────────────────────
# Main
#─────────────────────────────────────────────────────────────────

# retrieve this file location
pushd "$(dirname ${0})"
script_location=$(pwd)
popd

# read config
. $script_location/read-config-safe local $*

# Create shared directory with group and permissions accordingly
# to a config file
install_share

## vim: set filetype=zsh:
