#!/bin/zsh
#─────────────────────────────────────────────────────────────────
# Initialize a local directories hierarchy
#
# author:  Ludovic Vigouroux <ludo@mundoludo.fr>
# created: October 2011
#─────────────────────────────────────────────────────────────────

# retrieve this file location
pushd "$(dirname ${0})"
script_location=$(pwd)
popd

#─────────────────────────────────────────────────────────────────
# Create directories and show all directories
#─────────────────────────────────────────────────────────────────
make_directories() {
   for dirpath in ${(ov)treepaths}; do
       # create folder
       if $write; then
         if [[ ! -d $dirpath ]]; then
           mkdir -pv $dirpath
         fi
         if [[ -n $perms ]]; then
           chmod -v $perms $dirpath
         fi
       else
         print -- $dirpath
       fi
   done
}

#─────────────────────────────────────────────────────────────────
# Main
#─────────────────────────────────────────────────────────────────
write=false
local opt;
while getopts w opt; do
  case $opt in
    (w)
      write=true
      ;;
    (\?)
      print Bad option, aborting.
      return 1
      ;;
  esac
done

# load directories path
. $script_location/traverse-tree -v $config >> /dev/null

make_directories

# vim: set filetype=zsh:
