#!/bin/zsh
#─────────────────────────────────────────────────────────────────
# Initialize a local directories hierarchy
#
# author:  Ludovic Vigouroux <ludo@mundoludo.fr>
# created: October 2011
# Free to use, modify and redistribute.
#─────────────────────────────────────────────────────────────────

#─────────────────────────────────────────────────────────────────
# Create directories and show all directories
#─────────────────────────────────────────────────────────────────
make_directories() {
	for dirpath in ${(ov)treepaths}; do
		# create folder
		if [[ ! -d $dirpath ]]; then
			mkdir -pv $dirpath
		fi
	done
}

#─────────────────────────────────────────────────────────────────
# Main
#─────────────────────────────────────────────────────────────────
# retrieve this file location
: ${script_location:=${0:A:h}}

# load directories path
. $script_location/traverse-tree -q $*

make_directories

# vim: set filetype=zsh:
