#!/bin/zsh
#─────────────────────────────────────────────────────────────────
# Initialize a local directories hierarchy
#
# usage:   init-dirs environment [config file]
#
# author:  Ludovic Vigouroux <ludo@mundoludo.fr>
# created: October 2011
#─────────────────────────────────────────────────────────────────
# retrieve this file location
pushd "$(dirname ${0})"
script_location=$(pwd)
popd

# load functions libraries
autoload -U colors; colors
source $script_location/check-system
source $script_location/translate-config

# options
quiet=false
pretend=false
while getopts q opt; do
    case $opt in
    	q) quiet=true ;;
    	p) pretend=true ;;
    esac
done

# retrieve environment
env=$1
if [[ -z $env ]]; then
	print -- Environement is needed. && return 1
fi

# retrieve config location
config=$2
# or set it to default value
[[ -z $config ]] && config=${script_location}"/initialyzor.cfg"

# clean path of config file
if [[ -f $config ]]; then
    pushd ${config:h}
    config=$(pwd)"/"${config:t}
    popd
else
    print -- Failed to load config file $config
    return 1
fi

# traverse tree
source $script_location/traverse-tree $env $config

#─────────────────────────────────────────────────────────────────
# Create directories and show all directories
#─────────────────────────────────────────────────────────────────
make_directories() {
   for dirpath in ${(ov)treepaths}; do
       # create folder
       if [[ false == $pretend ]] && [[ ! -d $dirpath ]]; then
           $quiet || print -- "Creating directory $dirpath"
           mkdir -p $dirpath
   else
       $quiet || print -- $dirpath
       fi
   done
}

#─────────────────────────────────────────────────────────────────
# Main
#─────────────────────────────────────────────────────────────────
make_directories

# vim: set filetype=zsh:
