#!/bin/zsh
#─────────────────────────────────────────────────────────────────
# Initialize a local directories hierarchy
#
# author:  Ludovic Vigouroux <ludo@mundoludo.fr>
# created: October 2011
#─────────────────────────────────────────────────────────────────
setopt null_glob

make_bookmarks() {
  local bookmarks
  local outputs

  # bookmark for every directories in treepath
  for key in ${(k)treepaths}; do
     cleanname=$(echo $key | sed 's/\W//g' | sed 's/[0-9]//g')
     outputs=($outputs $cleanname=$treepaths[$key])
     bookmarks=($bookmarks $cleanname)
     # and for every directories inside those
     for dir in ${treepaths[$key]}/*(/); do
       cleanname=$(echo ${dir:t} | sed 's/\W//g' | sed 's/[0-9]//g')
       outputs=($outputs $cleanname=\"$dir\")
       bookmarks=($bookmarks $cleanname)
     done
    done

    for line in ${(o)outputs}; do
      print -- "typeset -gx" $line
    done

    echo : $bookmarks
}

# retrieve this file location
pushd "$(dirname ${0})"
script_location=$(pwd)
popd

# load directories path
. $script_location/traverse-tree -q $*

make_bookmarks

# vim: set filetype=zsh:
