#!/bin/zsh
#─────────────────────────────────────────────────────────────────
# Install or reset an user
#
# AUTHOR:  Ludovic Vigouroux <ludo@mundoludo.fr>
# CREATED: January 2013
#─────────────────────────────────────────────────────────────────

pushd "$(dirname ${0})"
script_location=$(pwd)
popd
# read config command
default_config_user=$script_location/initializor.cfg
default_config_share=$script_location/initializor.share.cfg
home_config=$HOME/.initialyzor.cfg
home_config_share=$HOME/.initialyzor.share.cfg

config=$1
if [[ -z $config ]] && [[ -f $default_config_user ]]; then
  config=$default_config_user
  if [[ -z $config ]]; then
    print -- "Please, copy sample file in $default_config_user"
    print -- "Please, and eventually share sample file in $default_config_share"
    print -- "and edit those before running this command"
  fi
fi

# share installation
config_share=$2
if [[ -z $config_share ]] && [[ -f $default_config_share ]]; then
  config_share=$default_config_share
fi
if [[ -n $config_share ]]; then
  # create share
  sudo $script_location/init-share $config_share || exit 1

  # add user to share group
  if [[ -n $group_name ]] && ! groups | grep -q $group_name; then
     sudo gpasswd -a $myname $group_name || exit 1
  fi

  # show arborescence
  $script_location/traverse-tree $config_share
  # create arborescence
  $script_location/init-dirs $config_share

  # set permissions
  . $script_location/traverse-tree -q $config_share
	me=$(whoami)
	if [[ -n $root_location ]] && ! stat -c '%U' $root_location | grep -q $me; then
		sudo chown -v $me $root_location || exit 1
	fi
  if [[ -n $treepaths ]]; then
    for dirpath in ${(ov)treepaths}; do
			if stat -c '%U' $dirpath | grep -q $me; then
				if ! stat -c '%G' $dirpath | grep -q $group_name; then
      		sudo chgrp -v $group_name $dirpath || exit 1
				fi
      	sudo chmod -v 2770 $dirpath || exit 1
			fi
    done
  fi

  # load sources
  $script_location/init-src $config_share || exit 1

  # copy config files in user home
  [[ -f $home_config_share ]] && mv $home_config_share ${home_config_share}.bak
  cp $config $home_config_share
fi

# user installation
# show arborescence
$script_location/traverse-tree $config || exit 1
# create arborescence
$script_location/init-dirs $config || exit 1

# copy config files in user home
[[ -f $home_config ]] && mv $home_config ${home_config}.bak
cp $config $home_config

# load sources
$script_location/init-src $config || exit 1

# add links
$script_location/init-links $config || exit 1

# install externals
$script_location/init-externals $config || exit 1

# vim: set filetype=zsh:
