#!/bin/zsh
#─────────────────────────────────────────────────────────────────
# Retrieve various sources
#
# AUTHOR:  Ludovic Vigouroux <ludo@mundoludo.fr>
# CREATED: December 2011
#─────────────────────────────────────────────────────────────────

#─────────────────────────────────────────────────────────────────
# Clone sources
#─────────────────────────────────────────────────────────────────
retrieve_src() {

  for project in ${(ok)src}; do
    print -- $project
    local dir=$src_path/$project
    if [[ -d $dir ]]; then
      cd $dir && git pull
    else
      git clone $src[$project] $dir
    fi
  done
}

# retrieve this file location
pushd "$(dirname ${0})"
script_location=$(pwd)
popd

# read config command
. $script_location/read-config-safe src $*

# load directories path
. $script_location/traverse-tree -q $* 

local src_path=$treepathslabel[src]

retrieve_src

# vim: set filetype=zsh:
