#!/bin/zsh
#─────────────────────────────────────────────────────────────────
# Retrieve various sources
#
# AUTHOR:  Ludovic Vigouroux <ludo@mundoludo.fr>
# CREATED: December 2011
#─────────────────────────────────────────────────────────────────

#─────────────────────────────────────────────────────────────────
# Clone sources
#─────────────────────────────────────────────────────────────────
retrieve_src() {
	local destination
	local dir

  for project in ${(ok)src}; do
    print -- $project
		if [[ -n $src_destination && -n $src_destination[$project] ]]; then
			destination=$treepathslabel[$src_destination[$project]]
		else
			destination=$src_path
		fi
    dir=$destination/$project
		echo $dir
    if [[ -d $dir ]]; then
      echo cd $dir && git pull
    else
      echo git clone $src[$project] $dir
    fi
  done
}

# retrieve this file location
pushd "$(dirname ${0})"
script_location=$(pwd)
popd

# read config command
. $script_location/read-config-safe src src_destination $*

# load directories path
. $script_location/traverse-tree -q $*

local src_path=$treepathslabel[src]

retrieve_src

# vim: set filetype=zsh:
