#!/bin/zsh
#─────────────────────────────────────────────────────────────────
# Translate values in a config section in zsh parameters
# Safe version of read-config, the one to source
#
# author:  Ludovic Vigouroux <ludo@mundoludo.fr>
# created: 2013-01-20
# Free to use, modify and redistribute.
#─────────────────────────────────────────────────────────────────
: ${script_location:=${0:A:h}}
# check system now
$script_location/check-system -q

args_withoutopts=(${*:#-*})

readconfig_cmd=($script_location/read-config $args_withoutopts)
if ! $readconfig_cmd > /dev/null; then
	$readconfig_cmd
	exit
fi

# set variables from config file
defaultIFS=$IFS
local IFS=""
for line in \
	$($readconfig_cmd)
do
	eval $line
done
local IFS=$defaultIFS

# vim: set filetype=zsh:
