#!/bin/zsh
#─────────────────────────────────────────────────────────────────
# Install externals sources
#
# AUTHOR:  Ludovic Vigouroux <ludo@mundoludo.fr>
# CREATED: January 2013
#─────────────────────────────────────────────────────────────────

# retrieve this file location
pushd "$(dirname ${0})/.."
script_location=$(pwd)
popd
default_config_share=$script_location/initializor.share.cfg
home_config_share=$HOME/.initialyzor.share.cfg

# read config command
. $script_location/load-config paths_file initializor $*

# add initializor to path
$script_location/export-path initializor $* >> $paths_file

bookmarks_file=$initializor[bookmarks_file];
# bookmarks
if [[ -n $bookmarks_file ]]; then
	rm -f $bookmarks_file

	# share
	if [[ -f $home_config_share ]]; then
		config_share=$home_config_share
	else
		if [[ -f $default_config_share ]]; then
			config_share=$default_config_share
		fi
	fi
	if [[ -n $config_share ]]; then
		$script_location/init-bookmarks $config_share > $bookmarks_file
	fi

	# home
	if [[ -f $bookmarks_file ]]; then
		$script_location/init-bookmarks $* >> $bookmarks_file
	else
		$script_location/init-bookmarks $* > $bookmarks_file
	fi
fi

# vim: set filetype=zsh:
