#!/bin/sh
#─────────────────────────────────────────────────────────────────
# Check system and setup global variables accordingly
#
# Author:  Ludovic Vigouroux <ludo@mundoludo.fr>
# Created: 2012-03-11
#─────────────────────────────────────────────────────────────────

check-system () {
	typeset -g BSD=false
	typeset -g DARWIN=false
	typeset -g UBUNTU=false
	# What is my system?
	if [[ $OSTYPE == darwin* ]]; then
			BSD=true
			DARWIN=true
			# use gnu commands in cross-platform scripts
			alias ln=gln
			alias mkdir=gmkdir
			alias chmod=gchmod
			alias chown=gchown
			alias chgrp=gchgrp
			alias touch=gtouch
			alias stat=gstat
			alias sed=gsed
	else
			uname -a | grep -q Ubuntu && UBUNTU=true
	fi
}

# vim: set filetype=zsh:
